# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_squashed_0004_auto_20160802_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmechanic',
            name='effect_size',
            field=models.FloatField(),
        ),
    ]
