# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmechanic',
            old_name='max_value',
            new_name='effect_size',
        ),
        migrations.RemoveField(
            model_name='cardmechanic',
            name='min_value',
        ),
        migrations.AlterUniqueTogether(
            name='cardmechanic',
            unique_together=set([('card', 'mechanic')]),
        ),
    ]
