# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160731_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='value',
            new_name='complex_value',
        ),
    ]
