# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_simple_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.FloatField(),
        ),
    ]
