# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20160802_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cost',
            new_name='mana',
        ),
    ]
