# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20160802_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
