# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
